cherrywajelly/frontend

.eslintrc.json
.prettierrc
package.json
src/app/layout.tsx
src/components/common-components/button/Button.tsx
src/components/common-components/button/Button.types.ts
src/components/common-components/button/index.ts
tailwind.config.ts
yarn.lock

이슈 번호 : #2 
- 타이포 세팅
- 컬러 세팅
- 버튼 컴포넌트 디자인 시스템 추가
- import order prettier rule 추가
- 디자인 시스템이 올바르게 세팅되었는지 확인해주세요.
- 버튼 컴포넌트의 확장성을 잘 고려하였는지 함께 고민해주세요 :>
(skip)
<br/>
---

setting/#2/design system - 디자인 시스템 세팅

---

src/api/index.ts
src/api/login.ts
src/app/api/v1/login/kakao/page.tsx
src/app/login/page.tsx
src/app/page.tsx
src/hooks/api/useLogin.ts
src/types/index.ts

이슈 번호 : #1 
- 로그인 페이지 추가 (임시라 추후 디자인 적용 예정)
- 카카오 로그인 로직 구현
- 디자인 나오고 다시 버튼 배치할거라 그부분 감안하고 봐주시면 좋을 것 같습니다~
<br/>
---

feat/#1/kakao-login: 카카오 로그인 구현

---

.eslintrc.json
src/app/lab/page.tsx
src/components/toast/ToastBox.tsx
tailwind.config.ts

이슈 번호 : #19 
- 토스트박스 컴포넌트 제작 (버튼 있는 경우/버튼 없는 경우 고려)
- 기존에 잘못 작성되어 있던 text-body1 font-size를 수정하였습니다.
<br/>
---

feat/#19/toast box: 토스트박스

---

src/api/setting.ts
src/app/lab/page.tsx
src/app/mypage/page.tsx
src/app/profile/[nickname]/page.tsx
src/app/setting/group/page.tsx
src/components/common-components/top-bar/TobBar.tsx
src/components/mypage/MyEventToastItem.tsx
src/components/mypage/MyGiftToastItem.tsx
src/components/mypage/Showcase.tsx
src/components/mypage/UserInfo.tsx
src/components/search/UserListItem.tsx
src/containers/mypage/MyFeed.tsx
src/containers/mypage/MyInfo.tsx
src/containers/setting/AddGroupUser.tsx
src/containers/setting/GenerateGroup.tsx
src/hooks/api/useSetting.ts
src/types/api/setting.ts
src/types/mypage.ts
src/types/user.ts

이슈 번호 : #21 
- `app/mypage`: 마이페이지
- `setting/group`: 그룹 설정 페이지
- `components/mypage`: 마이페이지에서 사용되는 atom component or molecule component
- `containers/mypage`: 마이페이지에서 활용되는 container
- `types/mypage.ts`: 마이페이지에서 사용되는 prop type 정의 
<br/>
---

feat/#21/mypage: mypage ui

---

src/app/search/page.tsx
src/atoms/componentAtom.tsx
src/components/common-components/bottom-bar/BottomBar.tsx
src/components/common-components/bottom-bar/BottomBar.types.ts
src/containers/setting/AddGroupUser.tsx

이슈 번호 : #26 
- 검색 페이지 추가
- 바텀바 상태 관리 관련 로직 변경
<br/>
---

feat/#26/search: 검색 페이지

---

src/app/lab/page.tsx
src/components/common-components/dropdown/Dropdown.tsx
src/components/common-components/dropdown/Dropdown.types.ts
src/components/common-components/dropdown/index.ts

이슈 번호 : #24 
[삭제하기] 및 [설정 드롭다운]에 사용될 컴포넌트
- 드롭다운 컴포넌트 작업
- 타입 지정
- props 추가
<br/>
---

feat/#24/dropdown component: 드롭다운 컴포넌트

---

src/api/signup.ts
src/app/api/v1/login/google/page.tsx
src/app/api/v1/login/kakao/page.tsx
src/app/sign-up/page.tsx
src/hooks/api/useSignUp.ts

이슈 번호 : #17 
- 닉네임 중복 검증 api 연동
- 닉네임 등록 (i.e. 회원가입) api 연동
<br/>
---

feat/#17/signup api: nickname 관련 api 연동

---

src/api/eventToast.ts
src/api/giftToast.ts
src/api/mypage.ts
src/api/setting.ts
src/api/signup.ts
src/app/mypage/follow/page.tsx
src/app/mypage/page.tsx
src/app/mypage/showcase/page.tsx
src/app/search/page.tsx
src/app/setting/group/create/page.tsx
src/app/setting/group/page.tsx
src/app/setting/profile/page.tsx
src/app/sign-up/page.tsx
src/components/common-components/top-bar/TobBar.tsx
src/components/common-components/top-bar/TopBar.types.ts
src/components/mypage/MyEventToastItem.tsx
src/components/mypage/UserInfo.tsx
src/containers/mypage/FollowTab.tsx
src/containers/mypage/MyFeed.tsx
src/containers/mypage/MyInfo.tsx
src/containers/setting/AddGroupUser.tsx
src/containers/setting/GroupList.tsx
src/hooks/api/useEventToast.ts
src/hooks/api/useGiftToast.ts
src/hooks/api/useMyPage.ts
src/hooks/api/useSignUp.ts
src/types/mypage.ts
tailwind.config.ts

이슈 번호 : #30 
- 마이페이지 api 연동
- 이벤트토스트 및 선물토스트 api 로직 작성
<br/>
---

feat/#30/mypage UI api: 마이페이지 관련 UI 및 API 연동

---

src/app/layout.tsx
src/middleware.ts

🌈 Update: modified matcher

---

src/app/event-toast/[eventToastId]/share/page.tsx

🌈 Update: modified typo

---

src/app/page.tsx

🌈 Update: remove comment

---

package.json
src/api/login.ts
src/api/payments.ts
src/app/api/v1/payments/fail/page.tsx
src/app/api/v1/payments/success/page.tsx
src/app/layout.tsx
src/app/page.tsx
src/app/setting/market/[iconGroupId]/page.tsx
src/app/setting/premiums/page.tsx
src/components/alert/ConfirmDialog.tsx
src/components/common-components/button/Button.tsx
src/components/payments/PayButton.tsx
src/containers/payments/FailArea.tsx
src/containers/payments/SuccessArea.tsx
src/containers/premiums/PremiumsInfo.tsx
src/hooks/api/usePayments.ts
src/types/api/payments.ts
src/utils/payments.ts
yarn.lock

feat/#126/pay system: 결제 시스템 구현

---

src/api/eventToast.ts
src/api/setting.ts
src/app/bake/event-toast/page.tsx
src/app/event-toast/[eventToastId]/share/page.tsx
src/app/setting/inquiry/page.tsx
src/hooks/api/useEventToast.ts
src/hooks/api/useSetting.ts
src/types/api/eventToast.ts
src/types/api/setting.ts

이슈 번호 : #131 
- share templates 관련 api 연결 및 훅 추가
- 공유 템플릿 화면 layout update
<br/>
---

feat/#131/inquiry share: 문의 및 공유 템플릿

---

src/app/search/page.tsx
src/app/setting/group/page.tsx
src/components/toast/TargetDivider.tsx
src/containers/mypage/FollowTab.tsx
src/containers/setting/AddGroupUser.tsx
src/containers/setting/GroupList.tsx
src/containers/write-toast/gift-toast/GiftToastWithChoiceForm.tsx

이슈 번호 : #132 
- TargetDivider 컴포넌트 추가
- 그룹 관리에서 검색 기능 추가
- 검색바 스타일링 이슈 수정
<br/>
---

feat/#132/group renewal: 그룹 리뉴얼

---

src/api/premiums.ts
src/app/gift-toast/[giftToastId]/page.tsx
src/app/home/page.tsx
src/app/mypage/page.tsx
src/app/profile/[memberId]/page.tsx
src/app/search/page.tsx
src/app/setting/account/page.tsx
src/app/setting/market/[iconGroupId]/page.tsx
src/app/setting/premiums/page.tsx
src/components/common-components/bottom-bar/BottomBar.tsx
src/components/common-components/top-bar/TobBar.tsx
src/containers/payments/FailArea.tsx
src/containers/payments/SuccessArea.tsx
src/containers/premiums/PremiumsInfo.tsx
src/hooks/api/usePremiums.ts
src/types/api/iconGroups.ts

update/#134/pay confirm: pay-system 최종 컨펌

---

src/app/event-toast/[eventToastId]/page.tsx
src/app/event-toast/[eventToastId]/share/page.tsx

fix/#137/issue-qa: 자가 QA 및 이슈 수정

---

src/app/event-toast/[eventToastId]/share/page.tsx
src/app/gift-toast/[giftToastId]/page.tsx

temp commit for applied env

---

public/firebase-messaging-sw.js
src/app/setting/account/page.tsx
src/app/setting/market/[iconGroupId]/page.tsx
src/containers/payments/SuccessArea.tsx
src/containers/setting/GenerateGroup.tsx
src/containers/write-toast/gift-toast/GiftToastWithChoiceForm.tsx
src/types/api/login.ts

self-qa issue

---

src/app/setting/market/page.tsx
src/app/setting/premiums/page.tsx
src/containers/write-toast/gift-toast/GiftToastOpenDateForm.tsx

🌈 Update(#137): modified logic and style

---

src/app/event-toast/[eventToastId]/share/page.tsx
src/app/layout.tsx
src/app/login/page.tsx

이미지 다운로드 ios 기기 테스트

---

src/app/event-toast/[eventToastId]/share/page.tsx

🌈 Update(#137): rollback

---

src/app/event-toast/[eventToastId]/share/page.tsx

✅ Test(#137): test img-download case

---

src/app/event-toast/[eventToastId]/page.tsx
src/app/event-toast/[eventToastId]/share/page.tsx
src/app/setting/inquiry/page.tsx

✅ Test(#137): test layout

---

src/app/api/v1/payments/fail/page.tsx
src/app/api/v1/payments/success/page.tsx
src/app/event-toast/[eventToastId]/share/page.tsx
src/containers/payments/FailArea.tsx

이슈 수정(기기 뷰포트 사이즈 이슈, 및 결제 관련 백라우팅)

---

src/app/event-toast/[eventToastId]/page.tsx
src/app/home/page.tsx
src/app/login/page.tsx
src/containers/payments/FailArea.tsx

결제 후 백라우팅 및 로직 이슈 수정

---

src/app/api/v1/payments/fail/page.tsx
src/app/api/v1/payments/success/page.tsx
src/app/bake/event-toast/page.tsx
src/app/bake/gift-toast/page.tsx
src/app/login/page.tsx
src/app/profile/[memberId]/page.tsx
src/app/setting/profile/page.tsx
src/containers/payments/FailArea.tsx
src/containers/payments/SuccessArea.tsx

이슈 수정 (기기 뷰포트 및 라우팅 관련)

---

src/app/api/v1/payments/fail/page.tsx
src/containers/payments/FailArea.tsx

test fail-page layout

---

src/app/event-toast/[eventToastId]/share/page.tsx

test share-logic

---

src/app/event-toast/[eventToastId]/share/page.tsx

🌈 Update(#137): test logic

---

src/app/event-toast/[eventToastId]/share/page.tsx

test issue

---

src/app/mypage/follow/page.tsx
src/containers/payments/SuccessArea.tsx

🌈 Update(#137): modified div style

---

public/firebase-messaging-sw.js

fcm logic response type 변경

---

public/firebase-messaging-sw.js
src/containers/payments/FailArea.tsx
src/containers/payments/SuccessArea.tsx
src/containers/write-toast/gift-toast/GiftToastWithChoiceForm.tsx
src/hooks/api/useMyPage.ts

이슈 번호 : #137 
- success page layout
- fail page layout
<br/>
---

fix/#137/issue qa: 이슈 수정(결제 결과 페이지)

---

src/components/toast/TargetDivider.tsx
src/containers/setting/GroupList.tsx

이슈 수정 및 dev배포 (12/05 - 03:50)

---

src/containers/write-toast/event-toast/EventToastOpenDateForm.tsx
src/containers/write-toast/gift-toast/GiftToastOpenDateForm.tsx

🌈 Update: modified text

---

src/app/event-toast/[eventToastId]/page.tsx

fix by adding bottom-bar about share-page

---

src/app/mypage/follow/page.tsx
src/app/mypage/showcase/page.tsx
src/app/setting/account/page.tsx
src/app/setting/group/create/page.tsx
src/app/setting/group/page.tsx
src/app/setting/inquiry/page.tsx
src/app/setting/market/[iconGroupId]/page.tsx
src/app/setting/market/page.tsx
src/app/setting/premiums/page.tsx
src/app/setting/profile/page.tsx
src/app/sign-up/page.tsx
src/containers/mypage/MyFeed.tsx
src/containers/setting/GenerateGroup.tsx

이슈 번호 : #171 
- 토스트 검색 기능 추가
- viewport size 레이아웃 수정(설정 페이지 관련)
<br/>
---

fix/#171/issue-softcon: 피드백 이슈 수정

---

src/api/eventToast.ts
src/api/giftToast.ts
src/app/bake/event-toast/page.tsx
src/app/bake/gift-toast/page.tsx
src/app/event-toast/[eventToastId]/page.tsx
src/app/gift-toast/[giftToastId]/page.tsx
src/atoms/toastAtom.ts
src/components/toast/ToastBox.tsx
src/containers/home/ArriveEventToast.tsx
src/containers/write-toast/event-toast/EventToastNameForm.tsx
src/containers/write-toast/gift-toast/GiftToastNameForm.tsx
src/types/api/eventToast.ts
src/types/api/giftToast.ts
src/types/atoms/toastAtom.ts

이슈 번호 : #171 
- 토스트 description 필드 추가
- atom 변경
- 토스트 team members (iswritten 관련) response type 추가 및 로직 수정
<br/>
---

fix/#171/issue softcon: toast response type 로직 변경 적용

---

src/containers/write-toast/ToastDecoForm.tsx
src/containers/write-toast/event-toast/EventToastNameForm.tsx
src/containers/write-toast/event-toast/EventToastOpenDateForm.tsx
src/containers/write-toast/gift-toast/GiftToastNameForm.tsx
src/containers/write-toast/gift-toast/GiftToastOpenDateForm.tsx
src/containers/write-toast/gift-toast/GiftToastWithChoiceForm.tsx

🌈 Update(#171): modified h-full to h-svh

---

src/app/bake/event-toast/page.tsx
src/app/bake/gift-toast/page.tsx
src/app/home/page.tsx

✅ Test(#171): test height

---

src/app/bake/event-toast/page.tsx
src/app/event-toast/[eventToastId]/jam/[jamId]/page.tsx
src/app/event-toast/[eventToastId]/page.tsx
src/app/event-toast/[eventToastId]/share/page.tsx
src/app/event-toast/[eventToastId]/write/page.tsx
src/app/home/page.tsx
src/app/mypage/follow/page.tsx
src/app/mypage/page.tsx
src/app/mypage/showcase/page.tsx
src/app/notifications/page.tsx
src/app/page.tsx
src/app/search/page.tsx
src/app/setting/group/create/page.tsx
src/app/setting/group/page.tsx
src/app/setting/inquiry/page.tsx
src/app/setting/market/[iconGroupId]/page.tsx
src/app/setting/market/page.tsx
src/app/setting/premiums/page.tsx
src/app/setting/profile/page.tsx
src/app/sign-up/page.tsx
src/containers/write-toast/ToastDecoForm.tsx
src/containers/write-toast/event-toast/EventToastNameForm.tsx
src/containers/write-toast/event-toast/EventToastOpenDateForm.tsx
src/containers/write-toast/gift-toast/GiftToastNameForm.tsx
src/containers/write-toast/gift-toast/GiftToastOpenDateForm.tsx
src/containers/write-toast/gift-toast/GiftToastWithChoiceForm.tsx

🌈 Update(#171): rollback about layout height

---

src/components/common-components/button/Button.tsx

fix the issue by removing duplicated property of button-component file

🔨 Fix: remove duplicated property about button file
